#!/bin/bash

# Clear the terminal
clear

# Print the Star Wars intro text using cowsay and lolcat
cowsay -f stegosaurus "A long time ago in a galaxy far, far away..."
echo ""
echo "It is a period of civil war. Rebel spaceships, striking"
echo "from a hidden base, have won their first victory against"
echo "the evil Galactic Empire."
echo ""
echo "During the battle, Rebel spies managed to steal secret"
echo "plans to the Empire's ultimate weapon, the DEATH STAR,"
echo "an armored
